version: '3.8'

services:
  registry:
    image: registry:2
    ports:
      - "5002:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
    volumes:
      - ./certs:/certs
      - ./auth:/auth
      - ./data:/var/lib/registry

volumes:
  certs:
  auth:
  data: