apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-creator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cronjob-creator-role
rules:
  - apiGroups: [ "batch" ]
    resources: [ "cronjobs" ]
    verbs: [ "create", "get", "list", "watch", "delete", "update" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-creator-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cronjob-creator
    namespace: default
roleRef:
  kind: Role
  name: cronjob-creator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob-proxy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronjob-proxy-server
  template:
    metadata:
      labels:
        app: cronjob-proxy-server
    spec:
      serviceAccountName: cronjob-creator
      containers:
        - name: cronjob-proxy-server
          image: craftsangjae/cronjob-proxy-server:0.0.3
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: cronjob-proxy-server
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8000
  selector:
    app: cronjob-proxy-server