apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "mnt/data/registry"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: certs
              mountPath: "/certs"
            - name: auth
              mountPath: "/auth"
            - name: data
              mountPath: "/var/lib/registry"
          env:
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/certs/domain.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/certs/domain.key"
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
      volumes:
        - name: certs
          secret:
            secretName: registry-certs
        - name: auth
          secret:
            secretName: registry-htpasswd
        - name: data
          persistentVolumeClaim:
            claimName: registry-data-claim

---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: ClusterIP  # 또는 LoadBalancer, 클러스터 설정에 따라 변경
  ports:
    - port: 4999
      targetPort: 5000
      protocol: TCP
  selector:
    app: registry